const swaggerJSDoc = require('swagger-jsdoc');

const response = (description, dataSchema) => ({
  description,
  content: {
    'application/json': {
      schema: {
        allOf: [
          { $ref: '#/components/schemas/ApiResponse' },
          ...(dataSchema ? [{ type: 'object', properties: { data: dataSchema } }] : []),
        ],
      },
    },
  },
});

const idParameter = {
  name: 'id',
  in: 'path',
  required: true,
  description: 'MongoDB ObjectId of the service request.',
  schema: { type: 'string', pattern: '^[a-fA-F0-9]{24}$' },
};

const swaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: 'Osta Marketplace API',
    version: '1.0.0',
    description: 'Authentication, authorization, and customer service-request API for the Osta marketplace.',
  },
  servers: [{ url: 'http://localhost:5009', description: 'Local development server' }],
  tags: [
    { name: 'Health', description: 'Service availability' },
    { name: 'Authentication', description: 'Registration, sessions, and account security' },
    { name: 'Admin', description: 'Administrator-only endpoints' },
    { name: 'Service Requests', description: 'Customer service-request management and lifecycle' },
    { name: 'Crafts', description: 'Public crafts catalogue' },
    { name: 'Artisans', description: 'Artisan discovery and profiles' },
    { name: 'Offers', description: 'Offer lifecycle between artisans and customers' },
    { name: 'Market', description: 'Public jobs market and stats' },
    { name: 'Contact', description: 'Contact-us messages' },
    { name: 'Wallet', description: 'Wallet balance and transactions' },
    { name: 'Users', description: 'Own profile management' },
    { name: 'Reviews', description: 'Ratings on completed work' },
  ],
  paths: {
    '/health': { get: { tags: ['Health'], summary: 'Check API health', operationId: 'getHealth', responses: { 200: response('Server is healthy') } } },
    '/api/auth/register': { post: { tags: ['Authentication'], summary: 'Register a customer or artisan', operationId: 'register', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RegisterRequest' } } } }, responses: { 201: response('Registration successful', { $ref: '#/components/schemas/User' }), 400: response('Validation error'), 409: response('Email or phone already exists') } } },
    '/api/auth/login': { post: { tags: ['Authentication'], summary: 'Log in and create a session', operationId: 'login', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoginRequest' } } } }, responses: { 200: response('Login successful', { $ref: '#/components/schemas/AuthData' }), 400: response('Validation error'), 401: response('Invalid credentials') } } },
    '/api/auth/logout': { post: { tags: ['Authentication'], summary: 'Log out the current session', operationId: 'logout', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Logged out successfully'), 401: response('Authentication required') } } },
    '/api/auth/logout-all': { post: { tags: ['Authentication'], summary: 'Revoke all active sessions', operationId: 'logoutAll', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('All sessions revoked'), 401: response('Authentication required') } } },
    '/api/auth/me': { get: { tags: ['Authentication'], summary: 'Get the current user profile', operationId: 'getCurrentUser', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Profile returned', { $ref: '#/components/schemas/User' }), 401: response('Authentication required') } } },
    '/api/auth/refresh': { post: { tags: ['Authentication'], summary: 'Rotate the refresh token', operationId: 'refreshToken', requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/RefreshRequest' } } } }, responses: { 200: response('Token refreshed', { $ref: '#/components/schemas/AuthData' }), 401: response('Invalid or expired refresh token') } } },
    '/api/auth/change-password': { patch: { tags: ['Authentication'], summary: 'Change the current password', operationId: 'changePassword', security: [{ bearerAuth: [] }, { cookieAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ChangePasswordRequest' } } } }, responses: { 200: response('Password changed'), 400: response('Validation or current-password error'), 401: response('Authentication required') } } },
    '/api/auth/forgot-password': { post: { tags: ['Authentication'], summary: 'Request a password reset', operationId: 'forgotPassword', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/EmailRequest' } } } }, responses: { 200: response('Generic reset response'), 400: response('Validation error') } } },
    '/api/auth/reset-password': { post: { tags: ['Authentication'], summary: 'Set a new password using a reset token', operationId: 'resetPassword', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ResetPasswordRequest' } } } }, responses: { 200: response('Password reset'), 400: response('Invalid or expired reset token') } } },
    '/api/auth/verify-email': { post: { tags: ['Authentication'], summary: 'Verify an email address', operationId: 'verifyEmail', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/TokenRequest' } } } }, responses: { 200: response('Email verified'), 400: response('Invalid or expired verification token') } } },
    '/api/admin/test': { get: { tags: ['Admin'], summary: 'Verify administrator access', operationId: 'testAdminAccess', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Admin access granted', { type: 'object', properties: { role: { type: 'string', example: 'admin' } } }), 401: response('Authentication required'), 403: response('Admin role required') } } },
    '/api/v1/requests': { post: { tags: ['Service Requests'], summary: 'Create a draft service request', operationId: 'createServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ServiceRequestInput' } } } }, responses: { 201: response('Draft created', { $ref: '#/components/schemas/ServiceRequest' }), 400: response('Validation error'), 401: response('Authentication required'), 403: response('Customer role required') } } },
    '/api/v1/requests/me': { get: { tags: ['Service Requests'], summary: "List the current customer's requests", operationId: 'listMyServiceRequests', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [{ $ref: '#/components/parameters/Page' }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Status' }, { $ref: '#/components/parameters/CraftId' }, { $ref: '#/components/parameters/Search' }, { $ref: '#/components/parameters/SortBy' }, { $ref: '#/components/parameters/SortOrder' }], responses: { 200: response('Requests returned', { $ref: '#/components/schemas/PaginatedRequests' }), 400: response('Invalid query'), 401: response('Authentication required') } } },
    '/api/v1/requests/{id}': { parameters: [idParameter], get: { tags: ['Service Requests'], summary: 'Get an owned service request', operationId: 'getServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Request returned', { $ref: '#/components/schemas/ServiceRequest' }), 401: response('Authentication required'), 404: response('Request not found') } }, patch: { tags: ['Service Requests'], summary: 'Update a draft or published request', operationId: 'updateServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ServiceRequestUpdate' } } } }, responses: { 200: response('Request updated', { $ref: '#/components/schemas/ServiceRequest' }), 400: response('Validation error'), 401: response('Authentication required'), 404: response('Request not found'), 409: response('Request cannot be updated in its current status') } } },
    '/api/v1/requests/{id}/publish': { post: { tags: ['Service Requests'], summary: 'Publish a draft request', operationId: 'publishServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter], responses: { 200: response('Request published', { $ref: '#/components/schemas/ServiceRequest' }), 401: response('Authentication required'), 404: response('Request not found'), 409: response('Invalid lifecycle transition') } } },
    '/api/v1/requests/{id}/cancel': { post: { tags: ['Service Requests'], summary: 'Cancel a published request', operationId: 'cancelServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CancelRequest' } } } }, responses: { 200: response('Request cancelled', { $ref: '#/components/schemas/ServiceRequest' }), 400: response('Validation error'), 409: response('Invalid lifecycle transition') } } },
    '/api/v1/requests/{id}/republish': { post: { tags: ['Service Requests'], summary: 'Republish a cancelled request', operationId: 'republishServiceRequest', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter], responses: { 200: response('Request republished', { $ref: '#/components/schemas/ServiceRequest' }), 409: response('Invalid lifecycle transition') } } },
    '/api/v1/requests/{id}/timeline': { get: { tags: ['Service Requests'], summary: 'Get request events oldest first', operationId: 'getServiceRequestTimeline', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter], responses: { 200: response('Timeline returned', { type: 'array', items: { $ref: '#/components/schemas/RequestEvent' } }), 404: response('Request not found') } } },
    '/api/v1/requests/{id}/images': { post: { tags: ['Service Requests'], summary: 'Upload request images', description: 'Accepts up to 10 JPEG, PNG, or WebP files. Each file is limited to 5 MB.', operationId: 'addServiceRequestImages', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter], requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: ['images'], properties: { images: { type: 'array', maxItems: 10, items: { type: 'string', format: 'binary' } } } } } } }, responses: { 201: response('Images uploaded', { type: 'array', items: { $ref: '#/components/schemas/RequestImage' } }), 400: response('Invalid or missing image files') } } },
    '/api/v1/requests/{id}/images/{imageId}': { delete: { tags: ['Service Requests'], summary: 'Delete a request image', operationId: 'deleteServiceRequestImage', security: [{ bearerAuth: [] }, { cookieAuth: [] }], parameters: [idParameter, { name: 'imageId', in: 'path', required: true, schema: { type: 'string' }, description: 'Image identifier stored on the request.' }], responses: { 200: response('Image deleted'), 404: response('Request or image not found') } } },
    '/api/v1/crafts': { get: { tags: ['Crafts'], summary: 'List crafts', operationId: 'listCrafts', responses: { 200: response('Crafts returned') } } },
    '/api/v1/artisans': { get: { tags: ['Artisans'], summary: 'Discover artisans', operationId: 'listArtisans', responses: { 200: response('Artisans returned') } } },
    '/api/v1/artisans/{id}': { get: { tags: ['Artisans'], summary: 'Get artisan profile + reviews', operationId: 'getArtisan', responses: { 200: response('Artisan returned'), 404: response('Not found') } } },
    '/api/v1/offers': { post: { tags: ['Offers'], summary: 'Artisan sends an offer', operationId: 'createOffer', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 201: response('Offer sent'), 409: response('Conflict') } } },
    '/api/v1/offers/mine': { get: { tags: ['Offers'], summary: 'Customer offers across own requests', operationId: 'myOffers', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Offers returned') } } },
    '/api/v1/offers/sent': { get: { tags: ['Offers'], summary: 'Artisan sent offers', operationId: 'sentOffers', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Offers returned') } } },
    '/api/v1/offers/{id}/accept': { post: { tags: ['Offers'], summary: 'Customer accepts an offer', operationId: 'acceptOffer', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Offer accepted') } } },
    '/api/v1/offers/{id}/reject': { post: { tags: ['Offers'], summary: 'Customer rejects an offer', operationId: 'rejectOffer', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Offer rejected') } } },
    '/api/v1/market': { get: { tags: ['Market'], summary: 'Public open jobs market', operationId: 'listMarket', responses: { 200: response('Market returned') } } },
    '/api/v1/market/stats': { get: { tags: ['Market'], summary: 'Public marketplace stats', operationId: 'marketStats', responses: { 200: response('Stats returned') } } },
    '/api/v1/contact': { post: { tags: ['Contact'], summary: 'Send a contact message', operationId: 'sendContact', responses: { 201: response('Message received') } } },
    '/api/v1/wallet': { get: { tags: ['Wallet'], summary: 'Wallet summary + transactions', operationId: 'walletSummary', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Wallet returned') } } },
    '/api/users/me': { patch: { tags: ['Users'], summary: 'Update own profile', operationId: 'updateMe', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Profile updated') } }, delete: { tags: ['Users'], summary: 'Deactivate own account', operationId: 'deleteMe', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Account deactivated') } } },
    '/api/v1/requests/{id}/review': { post: { tags: ['Reviews'], summary: 'Customer rates a request', operationId: 'submitReview', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 201: response('Review submitted') } } },
    '/api/admin/overview': { get: { tags: ['Admin'], summary: 'Admin overview stats', operationId: 'adminOverview', security: [{ bearerAuth: [] }, { cookieAuth: [] }], responses: { 200: response('Overview returned') } } },
  },
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Access token returned by login or refresh.' }, cookieAuth: { type: 'apiKey', in: 'cookie', name: 'accessToken', description: 'HTTP-only access-token cookie set by login or refresh.' } },
    parameters: {
      Page: { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, Limit: { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 10 } }, Status: { name: 'status', in: 'query', schema: { $ref: '#/components/schemas/RequestStatus' } }, CraftId: { name: 'craftId', in: 'query', schema: { type: 'string', pattern: '^[a-fA-F0-9]{24}$' } }, Search: { name: 'search', in: 'query', schema: { type: 'string', maxLength: 100 } }, SortBy: { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'updatedAt', 'title', 'status'], default: 'createdAt' } }, SortOrder: { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'], default: 'desc' } },
    },
    schemas: {
      ApiResponse: { type: 'object', required: ['success', 'message'], properties: { success: { type: 'boolean', example: true }, message: { type: 'string', example: 'Request completed successfully' }, data: { nullable: true } } },
      User: { type: 'object', properties: { _id: { type: 'string' }, name: { type: 'string' }, email: { type: 'string', format: 'email' }, phone: { type: 'string' }, role: { type: 'string', enum: ['customer', 'artisan', 'admin'] }, profileImage: { type: 'string' }, location: { type: 'string' }, isActive: { type: 'boolean' }, emailVerified: { type: 'boolean' }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } },
      RegisterRequest: { type: 'object', required: ['name', 'email', 'phone', 'password', 'role'], properties: { name: { type: 'string', minLength: 2, maxLength: 100 }, email: { type: 'string', format: 'email' }, phone: { type: 'string', minLength: 7, maxLength: 20 }, password: { type: 'string', format: 'password', minLength: 8, description: 'Must contain uppercase, lowercase, number, and symbol.' }, role: { type: 'string', enum: ['customer', 'artisan'] }, profession: { type: 'string' }, bio: { type: 'string', maxLength: 1000 }, experienceYears: { type: 'number', minimum: 0 }, skills: { type: 'array', items: { type: 'string' } }, serviceAreas: { type: 'array', items: { type: 'string' } }, hourlyRate: { type: 'number', minimum: 0 }, location: { type: 'string', maxLength: 200 } } },
      LoginRequest: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } }, AuthData: { type: 'object', properties: { user: { $ref: '#/components/schemas/User' }, accessToken: { type: 'string' } } }, RefreshRequest: { type: 'object', required: ['refreshToken'], properties: { refreshToken: { type: 'string' } } }, EmailRequest: { type: 'object', required: ['email'], properties: { email: { type: 'string', format: 'email' } } }, TokenRequest: { type: 'object', required: ['token'], properties: { token: { type: 'string' } } },
      ChangePasswordRequest: { type: 'object', required: ['currentPassword', 'newPassword'], properties: { currentPassword: { type: 'string', format: 'password' }, newPassword: { type: 'string', format: 'password', minLength: 8 } } }, ResetPasswordRequest: { type: 'object', required: ['token', 'newPassword'], properties: { token: { type: 'string' }, newPassword: { type: 'string', format: 'password', minLength: 8 } } }, Location: { type: 'object', required: ['city', 'area', 'address'], properties: { city: { type: 'string' }, area: { type: 'string' }, address: { type: 'string' }, latitude: { type: 'number', minimum: -90, maximum: 90 }, longitude: { type: 'number', minimum: -180, maximum: 180 } } }, Budget: { type: 'object', required: ['min', 'max'], properties: { min: { type: 'number', minimum: 0 }, max: { type: 'number', minimum: 0 }, currency: { type: 'string', enum: ['EGP'], default: 'EGP' } } },
      ServiceRequestInput: { type: 'object', required: ['title', 'description', 'craftId', 'location', 'budget'], properties: { title: { type: 'string', minLength: 3, maxLength: 200 }, description: { type: 'string', minLength: 10, maxLength: 5000 }, craftId: { type: 'string' }, location: { $ref: '#/components/schemas/Location' }, preferredDate: { type: 'string', format: 'date-time' }, preferredTime: { type: 'string', pattern: '^([01]\\d|2[0-3]):[0-5]\\d$' }, budget: { $ref: '#/components/schemas/Budget' }, receiveMode: { type: 'string', enum: ['OFFERS', 'DIRECT'] } } }, ServiceRequestUpdate: { type: 'object', minProperties: 1, properties: { title: { type: 'string', minLength: 3, maxLength: 200 }, description: { type: 'string', minLength: 10, maxLength: 5000 }, craftId: { type: 'string' }, location: { $ref: '#/components/schemas/Location' }, preferredDate: { type: 'string', format: 'date-time' }, preferredTime: { type: 'string' }, budget: { $ref: '#/components/schemas/Budget' }, receiveMode: { type: 'string', enum: ['OFFERS', 'DIRECT'] } } }, RequestStatus: { type: 'string', enum: ['DRAFT', 'PUBLISHED', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'AWAITING_PAYMENT', 'INSPECTION', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', 'EXPIRED'] },
      RequestImage: { type: 'object', properties: { _id: { type: 'string' }, url: { type: 'string' }, originalName: { type: 'string' }, mimeType: { type: 'string' }, size: { type: 'integer' } } }, ServiceRequest: { allOf: [{ $ref: '#/components/schemas/ServiceRequestInput' }, { type: 'object', properties: { _id: { type: 'string' }, customerId: { type: 'string' }, images: { type: 'array', items: { $ref: '#/components/schemas/RequestImage' } }, status: { $ref: '#/components/schemas/RequestStatus' }, publishedAt: { type: 'string', format: 'date-time', nullable: true }, cancelledAt: { type: 'string', format: 'date-time', nullable: true }, cancellationReason: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } }] }, RequestEvent: { type: 'object', properties: { _id: { type: 'string' }, type: { type: 'string' }, message: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' } } }, PaginatedRequests: { type: 'object', properties: { items: { type: 'array', items: { $ref: '#/components/schemas/ServiceRequest' } }, pagination: { type: 'object', properties: { page: { type: 'integer' }, limit: { type: 'integer' }, total: { type: 'integer' }, pages: { type: 'integer' } } } } }, CancelRequest: { type: 'object', required: ['reason'], properties: { reason: { type: 'string', minLength: 3, maxLength: 500 } } },
    },
  },
};

module.exports = swaggerJSDoc({ definition: swaggerDefinition, apis: [] });
